Update README file
IPECLabs/Ideas pull request #1
Opened 2018-08-20 18:21 UTC by nitish81299

2018-08-21 13:38 UTC, Ugtan requested changes

2018-08-21 13:38 UTC, Ugtan commented on README.md
> +* Could be an @ncurses interface or full @gui (maybe using @pyqt)
@nitish81299 change the @s format for links with [This is a link](LINK)

2018-08-21 14:33 UTC, mzfr commented
@nitish81299 Please make following changes:

1) Remove the `IP bot` and `online ranger` idea.
2) Keep the format similar as it was in google doc i.e indent the points that were indented.
3) Don't leave links in their full form shorten them using markdown syntax. See [create links in markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)

Refer to [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for help with markdown

2018-10-01 05:29 UTC, closed without merging

2018-10-01 05:29 UTC, mzfr commented
Toooo late brother